"""Internal helpers for custom elementary functions."""

from .callbacks import (
    build_custom_hessian_expr,
    build_custom_hvp_expr,
    build_custom_jacobian_expr,
    evaluate_custom_hessian,
    evaluate_custom_hvp,
    evaluate_custom_jacobian,
)
from .model import (
    PythonEvalBuilder,
    RegisteredElementaryFunction,
    ScalarHessianBuilder,
    ScalarHvpBuilder,
    ScalarJacobianBuilder,
    VectorHessianBuilder,
    VectorHvpBuilder,
    VectorJacobianBuilder,
    custom_scalar_hessian,
    custom_scalar_hvp,
    custom_scalar_jacobian,
    custom_vector_hessian_entry,
    custom_vector_hvp_component,
    custom_vector_jacobian_component,
)
from .registry import (
    clear_registered_elementary_functions,
    get_registered_elementary_function,
    parse_custom_scalar_args,
    parse_custom_scalar_hvp_args,
    parse_custom_vector_args,
    parse_custom_vector_hessian_entry_args,
    parse_custom_vector_hvp_component_args,
    parse_custom_vector_jacobian_component_args,
    register_elementary_function,
    render_custom_rust_snippet,
)

__all__ = [
    "PythonEvalBuilder",
    "RegisteredElementaryFunction",
    "ScalarHessianBuilder",
    "ScalarHvpBuilder",
    "ScalarJacobianBuilder",
    "VectorHessianBuilder",
    "VectorHvpBuilder",
    "VectorJacobianBuilder",
    "build_custom_hessian_expr",
    "build_custom_hvp_expr",
    "build_custom_jacobian_expr",
    "clear_registered_elementary_functions",
    "custom_scalar_hessian",
    "custom_scalar_hvp",
    "custom_scalar_jacobian",
    "custom_vector_hessian_entry",
    "custom_vector_hvp_component",
    "custom_vector_jacobian_component",
    "evaluate_custom_hessian",
    "evaluate_custom_hvp",
    "evaluate_custom_jacobian",
    "get_registered_elementary_function",
    "parse_custom_scalar_args",
    "parse_custom_scalar_hvp_args",
    "parse_custom_vector_args",
    "parse_custom_vector_hessian_entry_args",
    "parse_custom_vector_hvp_component_args",
    "parse_custom_vector_jacobian_component_args",
    "register_elementary_function",
    "render_custom_rust_snippet",
]
