"""gradgen package."""

from .ad import derivative, gradient, hessian, jacobian, jvp, vjp
from .cse import CSEAssignment, CSEPlan, cse
from .function import Function
from .rust_codegen import (
    CodeGenerationBuilder,
    FunctionBundle,
    RustBackendMode,
    RustBackendConfig,
    RustCodegenResult,
    RustDerivativeBundleResult,
    RustMultiFunctionProjectResult,
    RustProjectResult,
    RustScalarType,
    create_rust_derivative_bundle,
    create_multi_function_rust_project,
    create_rust_project,
    generate_rust,
)
from .simplify import simplify
from .sx import (
    SX,
    SXNode,
    SXVector,
    acos,
    asin,
    atan,
    const,
    cos,
    cosh,
    exp,
    expm1,
    log,
    log1p,
    maximum,
    sin,
    sinh,
    sqrt,
    tan,
    tanh,
    vector,
)

__all__ = [
    "CSEAssignment",
    "CSEPlan",
    "CodeGenerationBuilder",
    "Function",
    "FunctionBundle",
    "RustBackendMode",
    "RustBackendConfig",
    "RustCodegenResult",
    "RustDerivativeBundleResult",
    "RustMultiFunctionProjectResult",
    "RustProjectResult",
    "RustScalarType",
    "SX",
    "SXNode",
    "SXVector",
    "acos",
    "asin",
    "atan",
    "const",
    "cos",
    "cosh",
    "cse",
    "create_rust_project",
    "create_rust_derivative_bundle",
    "create_multi_function_rust_project",
    "derivative",
    "exp",
    "expm1",
    "gradient",
    "hessian",
    "jacobian",
    "jvp",
    "log",
    "log1p",
    "maximum",
    "generate_rust",
    "simplify",
    "sin",
    "sinh",
    "sqrt",
    "tan",
    "tanh",
    "vector",
    "vjp",
]
