on:
  push:
    branches: [ master ]
  pull_request:

name: Continuous integration

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
    env:
      DO_DOCKER: 0
    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-clang@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'      
      - run: bash ./ci/script.sh
