name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: "CI tests"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install package
        run: python -m pip install --upgrade pip && python -m pip install -e . numpy sympy pytest

      - name: Run tests
        run: pytest tests -v

      - name: Generate demo crates
        run: make -C demos/

      - name: Test Python-Rust interface
        run: python demos/python_interface/runner/main.py

      - name: Clippy for demo kernels
        run: |
          cargo clippy --quiet --manifest-path demos/codegen/codegen_kernel/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/custom_function/custom_function_kernel/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/map_zip/map_zip_kernel/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/multi_function/multi_function_kernel/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/vjp/runner/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/composed_function/composed_kernel/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/single_shooting/single_shooting_kernel/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/python_interface/foo_python/Cargo.toml -- -D warnings

      - name: Run demo runners
        run: |
          cargo run --manifest-path demos/codegen/runner/Cargo.toml 
          cargo run --manifest-path demos/custom_function/runner/Cargo.toml
          cargo run --manifest-path demos/map_zip/runner/Cargo.toml
          cargo run --manifest-path demos/multi_function/runner/Cargo.toml
          cargo run --manifest-path demos/vjp/runner/Cargo.toml
          cargo run --manifest-path demos/composed_function/runner/Cargo.toml
          cargo run --manifest-path demos/single_shooting/runner/Cargo.toml          

      - name: Clippy for demo runners
        run: |
          cargo clippy --quiet --manifest-path demos/codegen/runner/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/custom_function/runner/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/map_zip/runner/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/multi_function/runner/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/vjp/runner/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/composed_function/runner/Cargo.toml -- -D warnings
          cargo clippy --quiet --manifest-path demos/single_shooting/runner/Cargo.toml -- -D warnings
